dist: xenial
language: go
sudo: false
install:
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - go mod download
script:
  - golangci-lint run --enable-all -D lll -D errcheck
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
go:
  - 1.11.x
  - 1.12.x
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
